## Written by https://github.com/anthonysecco

sensor:
  - platform: rest
    name: US Public Lands Info
    unique_id: 21bdf81e-049b-4b80-aafc-1078edf2cb30
    resource_template: >
      {% set lat = state_attr('zone.home', 'latitude') | round(4) %}
      {% set lon = state_attr('zone.home', 'longitude') | round(4) %}
      https://services.arcgis.com/v01gqwM5QqNysAAi/arcgis/rest/services/PADUS_Public_Access/FeatureServer/0/query?geometry={{ lon }},{{ lat }}&geometryType=esriGeometryPoint&inSR=4326&outFields=Unit_Nm,Pub_Access,MngTp_Desc,MngNm_Desc,DesTp_Desc&returnGeometry=false&f=json
    method: GET
    value_template: "{{ value_json.features[0].attributes.Unit_Nm }}"
    json_attributes:
      - features
    scan_interval: 3600 # Refresh interval.  I don't suggest setting this to less than 300s.

template:
  - sensor:
      - name: "Unit Name"
        state: >
          {% if state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['Unit_Nm'] == "Non-PAD-US Area" %}
            Non-Protected Area
          {% else %}
            {{ state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['Unit_Nm'] }}
          {% endif %}
        icon: "mdi:map-marker-radius"

      - name: "Public Access"
        state: >
          {% set access_map = {
            'OA': 'Open to the Public',
            'RA': 'Restricted Access',
            'XA': 'Closed to the Public',
            'PA': 'Public Access by Permit',
            'TA': 'Temporary Access Allowed',
            'UK': 'Unknown'
          } %}
          {{ access_map.get(state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['Pub_Access'], 'Unknown Access Type') }}
        icon: "mdi:key"

      - name: "Management Type"
        state: "{{ state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['MngTp_Desc'] }}"
        icon: "mdi:account-tie-hat"

      - name: "Management Name"
        state: "{{ state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['MngNm_Desc'] }}"
        icon: "mdi:domain"

      - name: "Designation"
        state: "{{ state_attr('sensor.us_public_lands_info', 'features')[0]['attributes']['DesTp_Desc'] }}"
        icon: "mdi:pine-tree"
